watch_stylesheet: true
watch_config: true

# This is the main configuration file for Yet Another Status Bar (YASB)
bars:
  status-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    blur_effect:
      enabled: true
      acrylic: false
      dark_mode: false
      round_corners: false
      border_color: None
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 32
    padding:
      top: 0
      left: 0
      bottom: 0
      right: 0
    widgets:
      left: ["win_button", "apps", "active_window"]
      center: ["clock", "taskbar"]
      right: ["cava", "media", "weather", "systeminfo-grouper", "power_menu"]
widgets:
  media:
    type: "yasb.media.MediaWidget"
    options:
      label: "{title} - {artist}"
      label_alt: "{title}"
      max_field_size:
        label: 20
        label_alt: 30
      show_thumbnail: true
      controls_only: false
      controls_left: true
      hide_empty: true
      thumbnail_alpha: 60
      thumbnail_padding: 8
      thumbnail_corner_radius: 0 # Set to 0 for square corners
      icons:
        prev_track: "\ue892"
        next_track: "\ue893"
        play: "\ue768"
        pause: "\ue769"

  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[title]}"
      label_alt: "[class_name='{win[class_name]}' exe='{win[process][name]}' hwnd={win[hwnd]}]"
      label_no_window: ""
      label_icon: true
      label_icon_size: 16
      max_length: 36
      max_length_ellipsis: "..."
      monitor_exclusive: true

  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%a %#d, %b %#I:%M %p}"
      label_alt: "{%A %#d %B %Y, %#I:%M %p}"
      timezones: [] # Looking up time zone info from registry
      calendar:
        blur: True
        round_corners: True
        round_corners_type: "normal"
        border_color: "System"
        alignment: "center"
        direction: "down"
        distance: 12

  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "<span>\uf4bc</span> {info[percent][total]}%"
      label_alt: "<span>\uf437</span> {info[histograms][cpu_percent]}"
      update_interval: 2000
      histogram_icons:
        - "\u2581" # 0%
        - "\u2581" # 10%
        - "\u2582" # 20%
        - "\u2583" # 30%
        - "\u2584" # 40%
        - "\u2585" # 50%
        - "\u2586" # 60%
        - "\u2587" # 70%
        - "\u2588" # 80%+
      histogram_num_columns: 8
      callbacks:
        on_right: "exec cmd /c Taskmgr"

  memory:
    type: "yasb.memory.MemoryWidget"
    options:
      label: "<span>\uefc5</span> {virtual_mem_free}"
      label_alt: "<span>\uefc5</span> {virtual_mem_percent}%"
      update_interval: 10000
      callbacks:
        on_right: "exec cmd /c Taskmgr"

  wifi:
    type: "yasb.wifi.WifiWidget"
    options:
      label: "<span>{wifi_icon}</span>"
      label_alt: "{wifi_name} {wifi_strength}%"
      update_interval: 5000
      callbacks:
        on_left: "exec cmd.exe /c start ms-settings:network"
        on_middle: "do_nothing"
        on_right: "toggle_label"

  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      label: "<span>{icon}</span> {temp}"
      label_alt: "{location}: Min {min_temp}, Max {max_temp}, Humidity {humidity}"
      api_key: "3bf4cf9a7c3f40d6b31174128242807"
      update_interval: 600 # Update interval in seconds, Min 600 seconds
      hide_decimal: true
      location: "USA San Diego 92116"
      callbacks:
        on_left: "toggle_card"
        on_middle: "do_nothing"
        on_right: "toggle_label"
      icons:
        sunnyDay: "\ue30d"
        clearNight: "\ue32b"
        cloudyDay: "\udb81\udd99"
        cloudyNight: "\ue311"
        rainyDay: "\udb81\ude7e"
        rainyNight: "\udb81\ude7e"
        snowyIcyDay: "\udb81\udd98"
        snowyIcyNight: "\udb81\udd98"
        blizzardDay: "\uebaa"
        default: "\uebaa"
        # https://www.weatherapi.com/docs/
        # Usage {temp}, {min_temp}, {max_temp}, {temp_f}, {min_temp_f}, {max_temp_f}, {location}, {humidity}, {icon}, {conditions}
      weather_card:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "None"
        alignment: "right"
        icon_size: 64
        show_hourly_forecast: true
        time_format: "24h"
        hourly_point_spacing: 76
        hourly_icon_size: 32
        icon_smoothing: true
        temp_line_width: 2
        current_line_color: "#8EAEE8"
        current_line_width: 2
        current_line_style: "dot"
        weather_animation:
          enabled: true
          snow_overrides_rain: true
          temp_line_animation_style: both # can be "rain", "snow", "both", or "none"
          rain_effect_intensity: 1.0 # 0.01 - 10.0
          snow_effect_intensity: 1.0 # 0.01 - 10.0
          scale_with_chance: true
          enable_debug: false

  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "\uf011"
      uptime: True
      blur: False
      blur_background: True
      animation_duration: 300 # Milisecond
      button_row: 3 # Number of buttons in row, min 1 max 5
      buttons:
        lock: ["\uea75", "Lock"]
        signout: ["\udb80\udf43", "Sign out"]
        #sleep: ["\u23fe","Sleep"]
        shutdown: ["\uf011", "Shut Down"]
        restart: ["\uead2", "Restart"]
        hibernate: ["\uf28e", "Hibernate"]
        cancel: ["\udb81\udf3a", "Cancel"]
        # force_shutdown: ["\uf011","Force Shut Down"]
        # force_restart: ["\uead2","Force Restart"]

  apps:
    type: "yasb.applications.ApplicationsWidget"
    options:
      label: "{data}"
      app_list:
        - {
            icon: "\uf489",
            launch: "C:\\Program Files\\WezTerm\\wezterm-gui.exe",
          }
        - { icon: "\uf413", launch: "explorer c:\\Users\\Shibo" }
        # - { icon: "\uf0a2", launch: "notification_center" }
        # - { icon: "\ueb51", launch: "quick_settings" }
        - {
            icon: "\udb81\udd9f",
            launch: "C:\\Program Files (x86)\\BraveSoftware\\Brave-Browser\\Application\\brave.exe",
          }
        - {
            icon: "\uf1ff",
            launch: "C:\\Users\\Shibo\\AppData\\Local\\Discord\\Update.exe --processStart Discord.exe",
          }
        - {
            icon: "\uf1b6",
            launch: "D:\\Program Files (x86)\\Steam\\steam.exe",
          }
        - {
            icon: "\uec1b",
            launch: "D:\\Program Files (x86)\\WACUP\\wacup.exe",
          }
        #- {icon: "\uf46a", launch: "cmd.exe /c start ms-settings:windowsupdate"}
        # - { icon: "\uf422", launch: "search" }
        #- {icon: "\udb84\udf55", launch: "widget"}
        # Currently available to use quick_settings, notification_center, search, widget, launcher (launcher will trigger ALT+A)

  win_button:
    type: "yasb.custom.CustomWidget"
    options:
      label: "^_^"
      label_alt: "\ue62a"
      class_name: "system-widget"
      callbacks:
        on_left: "exec start_menu"

  gpu:
    type: "yasb.gpu.GpuWidget"
    options:
      label: "<span>\udb82\udcae</span> {info[utilization]}%"
      label_alt: "<span>\udb82\udcae</span> {info[temp]}Â°C | {info[mem_used]} / {info[mem_total]}"
      update_interval: 2000
      gpu_thresholds:
        low: 25
        medium: 50
        high: 90
      histogram_icons:
        - "\u2581" # 0%
        - "\u2581" # 10%
        - "\u2582" # 20%
        - "\u2583" # 30%
        - "\u2584" # 40%
        - "\u2585" # 50%
        - "\u2586" # 60%
        - "\u2587" # 70%
        - "\u2588" # 80%+
      histogram_num_columns: 8
      callbacks:
        on_left: "toggle_label"

  taskbar:
    type: "yasb.taskbar.TaskbarWidget"
    options:
      icon_size: 16
      tooltip: true
      show_only_visible: false
      strict_filtering: true
      monitor_exclusive: true
      animation:
        enabled: true
      preview:
        enabled: true
        width: 240
        delay: 400
        padding: 8
        margin: 8
      title_label:
        enabled: false
        show: "always"
        min_length: 10
        max_length: 30
      ignore_apps:
        processes: []
        titles: []
        classes: []

  cava:
    type: "yasb.cava.CavaWidget"
    options:
      bar_height: 12
      min_bar_height: 0
      gradient: 1
      foreground: "#89b4fa"
      gradient_color_1: "#74c7ec"
      gradient_color_2: "#89b4fa"
      gradient_color_3: "#cba6f7"
      bars_number: 8
      bar_spacing: 2
      bar_width: 4
      bar_type: "bars"
      framerate: 60
      hide_empty: true

  systeminfo-grouper:
    type: "yasb.grouper.GrouperWidget"
    options:
      class_name: "systeminfo-grouper"
      widgets: ["gpu", "cpu", "memory", "wifi"]
